language: php

php: [5.3.3, 5.3, 5.4, 5.5 , 5.6 , hhvm]

matrix:
    allow_failures:
        - php: 5.6
        - php: hhvm

before_script:
  - composer selfupdate
  - export COMPOSER_ROOT_VERSION=2.0.0-RC3
  - composer install --prefer-source
  - composer require --dev "satooshi/php-coveralls ~0.6"

script:
  - ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

after_script:
  - php ./vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml